"""add vote.priority

Revision ID: 15a162b93ce9
Revises: cfd6710f2ee1
Create Date: 2019-11-15 12:48:30.025167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15a162b93ce9"
down_revision = "cfd6710f2ee1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vote", sa.Column("priority", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vote", "priority")
    # ### end Alembic commands ###
