"""Add deleted flag to poll

Revision ID: dd18721adbcc
Revises: 9e39ba5d94c4
Create Date: 2019-06-16 04:51:55.372569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd18721adbcc"
down_revision = "9e39ba5d94c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "poll",
        sa.Column("deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("poll", "deleted")
    # ### end Alembic commands ###
