"""Remove unique constraint from username

Revision ID: c4feb636bb05
Revises: 6d9c67a35dad
Create Date: 2019-11-07 03:20:49.588022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c4feb636bb05"
down_revision = "6d9c67a35dad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_username_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_username_key", "user", ["username"])
    # ### end Alembic commands ###
