"""Due date on poll

Revision ID: b0789eb1e8a4
Revises: 6fa1efa202b3
Create Date: 2019-06-29 23:10:11.868929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0789eb1e8a4"
down_revision = "6fa1efa202b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("poll", sa.Column("due_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("poll", "due_date")
    # ### end Alembic commands ###
