"""External stats

Revision ID: c8c17d4869a8
Revises: 933060cd8eeb
Create Date: 2019-09-18 14:52:42.006646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8c17d4869a8"
down_revision = "933060cd8eeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_statistic",
        sa.Column(
            "externally_shared", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "daily_statistic",
        sa.Column("show_results", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_statistic", "show_results")
    op.drop_column("daily_statistic", "externally_shared")
    # ### end Alembic commands ###
