"""Add User flags

Revision ID: 6d9c67a35dad
Revises: 7783c1dc58f7
Create Date: 2019-11-07 01:15:14.106054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d9c67a35dad"
down_revision = "7783c1dc58f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("admin", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "user",
        sa.Column(
            "notifications_enabled", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "notifications_enabled")
    op.drop_column("user", "admin")
    # ### end Alembic commands ###
