"""Remove deleted flag

Revision ID: f80d0dd2ddac
Revises: 5a27262256bb
Create Date: 2019-07-02 17:15:16.589148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f80d0dd2ddac"
down_revision = "5a27262256bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("poll", "deleted")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "poll", sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
