"""Added created_from_native field to Poll

Revision ID: 1095210c0ba3
Revises: b7656826d33c
Create Date: 2020-05-30 00:18:49.477499

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1095210c0ba3"
down_revision = "b7656826d33c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "poll",
        sa.Column(
            "created_from_native",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
            default=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("poll", "created_from_native")
    # ### end Alembic commands ###
