"""User vote statistic

Revision ID: 07007a76f428
Revises: 8a4f079a3260
Create Date: 2020-04-24 03:08:08.100528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07007a76f428"
down_revision = "8a4f079a3260"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_statistic",
        sa.Column("votes", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_statistic", "votes")
    # ### end Alembic commands ###
