"""Reintroduce update.count

Revision ID: 7de7ec98049b
Revises: 5a8b94fb9dd9
Create Date: 2020-03-04 15:51:57.477697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7de7ec98049b"
down_revision = "5a8b94fb9dd9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "update", sa.Column("count", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("update", "count")
    # ### end Alembic commands ###
